### ISSUE TITLE
Rake Aborted on "rake DmgTask" 

### ISSUE THREAD

**Issue by saurabhhack123** [baldowl/rake_dmg#1]
I am getting following error on running  >rake DmgTask
rake aborted!
cannot load such file -- rake/dmg............

**Comment by saurabhhack123** [comment]
Now I installed rails gem , I am getting following error :
rake aborted!
undefined method `desc' for #Rake::DmgTask:0x000001011b56c8

**Comment by baldowl** [comment]
The latter issue is due to Rake's internals having changed a bit over the last four years; I'll try to allocate time to fix it over the weekend.

**Comment by saurabhhack123** [comment]
Thanks baldowl , waiting for this issue to get fix , stuck in the middle of the project .
